### PR TITLE
docs: adding explanation for the force flag at swagger

### PR DESCRIPTION
**Pull request by felipemontoya**
Adding the explanation for the swagger live documentation.

@MoisesGSalas this parameter is optional, should I mark that somewhere?

Post-Merge

- [ ]  does not require to be released inmediately

### CODE REVIEW

**Review by MoisesGSalas — APPROVED** [review]
There is no need to mark optional parameters, the approach we are taking is to indicate when a parameter is *required*.

**Comment by mariajgrimaldi** [comment]
can we merge this @MoisesGSalas ?

**Comment by MoisesGSalas** [comment]
> can we merge this @MoisesGSalas ?

@mariajgrimaldi, this could be expanded to include documentation about programs which is currently missing, as well as using the correct serializers for the docs (I think `EdxappCourseEnrollmentQuerySerializer` should be used instead `EdxappCourseEnrollmentSerializer`)

**Comment by MoisesGSalas** [comment]
Closed in favor of #170.

**Pull request closed without merging**
