### PR TITLE
feat: enable custom_reg_form capability

### PR DESCRIPTION
**Pull request by johanv26**
## Description
Enable the custom_reg_form.
The field could be used using the `EDNX_CUSTOM_REGISTRATION_FIELDS` setting.
Based in this edx-platform [logic](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L205) 
## Testing instructions

Add this setting with some fields related to an extended custom reg form.
``` json
    "EDNX_CUSTOM_REGISTRATION_FIELDS": [
        {
            "label": "arabicname",
            "name": "arabic_name",
            "type": "text"
        }
    ],
```
Post a user with the extra_field.
Check the user was created and in the extended custom reg model.

Peek 2023-11-16 14-38

If you add the field is also stored in the model and meta.
``` json
   "extended_profile_fields": [
        "arabic_name"
    ]
```
Peek 2023-11-16 14-46

## Additional information
This dont affect anything if you dont have defined the setting `REGISTRATION_EXTENSION_FORM`.
[setting management](https://github.com/openedx/edx-platform/blob/e5386df557909197b9d922909703092002c6d5e7/openedx/core/djangoapps/user_authn/views/registration_form.py#L304)
Other wise that definition would give the validation rules of that form to the endpoint. 
So with with a falsy value, the form works with previous behaviour.
Peek 2023-11-16 14-55

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by andrey-canon** [comment]
@johanv26 this didn't work for me, is something missing ?

https://github.com/eduNEXT/eox-core/assets/36200299/d39c4481-b248-419c-bb27-5f27f6837f12

**Comment by johanv26** [comment]
> @johanv26 this didn't work for me, is something missing ?
> 
> https://github.com/eduNEXT/eox-core/assets/36200299/d39c4481-b248-419c-bb27-5f27f6837f12
> 
> 
> 

@andrey-canon do you have this setting?
`REGISTRATION_EXTENSION_FORM`

**Comment by andrey-canon** [comment]
> REGISTRATION_EXTENSION_FORM

@johanv26 
image

**Comment by andrey-canon** [comment]
> REGISTRATION_EXTENSION_FORM

@johanv26 
image

**Comment by johanv26** [comment]
@andrey-canon I think I had to specify in the PR description how to enable the custom_reg_form.
By the moment, could you add 

```python
>>> settings.REGISTRATION_EXTENSION_FORM
'custom_reg_form.forms.ExtraInfoForm'
```

**Review by andrey-canon — APPROVED** [review]
I tested locally and worked

image
image

**Comment by andrey-canon** [comment]
@johanv26  could you open the pr against the master branch ? If you haven't done yet

**Comment by johanv26** [comment]
> @johanv26 could you open the pr against the master branch ? If you haven't done yet
> 
> btw I had to change the setting `EOX_CORE_USERS_BACKEND` since the default is `"eox_core.edxapp_wrapper.backends.users_l_v1"`

Ok I think that would work by default, but thank you for the explanation.

PR opened:
https://github.com/eduNEXT/eox-core/pull/256

**Pull request merged**
