### PR TITLE
Fixed relative import statements

### PR DESCRIPTION
**Pull request by shaidar**
Minor fixes to relative imports that are causing migration failures during the ansible run.

### CODE REVIEW

**Comment by felipemontoya** [comment]
Thanks @shaidar, we will review this shortly.

@andrey-canon and @mariajgrimaldi I tagged you both to see if you can review this. Would it create errors when we run this in older installations (hawthorn based for example)?

**Comment by mariajgrimaldi** [comment]
Hey there @felipemontoya and @shaidar! 

We encountered these issues while making eox-core forward compatible with lilac, to solve them we decided to create new backends for [user](https://github.com/eduNEXT/eox-core/blob/master/eox_core/edxapp_wrapper/backends/users_l_v1.py) and [pre-enrollment](https://github.com/eduNEXT/eox-core/blob/master/eox_core/edxapp_wrapper/backends/pre_enrollment_l_v1.py) and leave the current (working in juniper) defaults in [settings/common.py](https://github.com/eduNEXT/eox-core/blob/fa484526ab5cfeb160fd19f055a8d40a0444a6ea/eox_core/settings/common.py#L23).

So, what I recommend to avoid errors in other installations is to override settings/common.py with the correct backends for lilac.

@shaidar can you test changing EOX_CORE_USERS_BACKEND and EOX_CORE_PRE_ENROLLMENT_BACKEND?

For example:

EOX_CORE_USERS_BACKEND: "eox_core.edxapp_wrapper.backends.users_l_v1"
EOX_CORE_PRE_ENROLLMENT_BACKEND: "eox_core.edxapp_wrapper.backendspre_enrollment_l_v1"

**Comment by shaidar** [comment]
@mariajgrimaldi Great. Thanks for the info. Will give that a shot and let you know.

**Comment by mariajgrimaldi** [comment]
I added a new PR for the missing backend for enrollments #146. I'll let you know when it's approved!

**Comment by shaidar** [comment]
@mariajgrimaldi Looks like we need a new tag as the `4.8` one doesn't include the `users_l_v1` module. I can pull from master, but just thought I'd mention it.

**Comment by mariajgrimaldi** [comment]
Of course, I'll merge the enrollment backend and release the new tag. Thank you! @shaidar

**Comment by mariajgrimaldi** [comment]
The new tag is out! @shaidar :smile:

**Comment by mariajgrimaldi** [comment]
Master already supports lilac.

**Pull request closed without merging**
