### PR TITLE
feat: enable custom_reg_form capability

### PR DESCRIPTION
**Pull request by johanseto**
## Description

Enable the custom_reg_form. This is a feature of upstream openedx, and maybe for people like opencraft would like.
The field could be used using the `REGISTRATION_EXTENSION_FORM`   setting. https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L205

**Useful information to include:**
This is like a cherrypick of this PR: https://github.com/eduNEXT/eox-core/pull/256
Also, some logic has to be updated.
To know how this work with more explanation check this PR.
https://github.com/eduNEXT/eox-core/pull/253

## Testing instructions

https://github.com/eduNEXT/eox-core/pull/253
## Additional information

[Include anything else that will help reviewers and consumers understand the change.

- Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.](https://github.com/eduNEXT/eox-core/pull/253)

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by MaferMazu** [comment]
Hello, @johanv26, thanks for this feature. Only for better understanding:
- What is the current behavior around the custom registration forms?
- How does this PR modify the current behavior?
- Why do we want this?

**Comment by MaferMazu** [comment]
I tested it by adding in my tenant the following:
```
"EDNX_CUSTOM_REGISTRATION_FIELDS": [
        {
            "label": "arabicname",
            "name": "arabic_name",
            "type": "text"
        },
        {
            "label": "Organization name",
            "name": "org_name",
            "type": "text"
        }
    ],
   "extended_profile_fields": [
        "org_name",
        "arabic_name"
    ]
}
```
And then I made a request to create a user... and it created the user with the info in the meta... but I didn't need to set the `REGISTRATION_EXTENSION_FORM`. Is it the expected behavior?

cc @johanv26

**Comment by johanv26** [comment]
Hey @MaferMazu I think that is the expected behavior.
**What is the current behavior around the custom registration forms?**
Custom reg form is something related extension in order to save extra custom fields defined in a model. This extra data would be saved in that custom_reg_form model. 
This is an [example](https://github.com/open-craft/custom-registration-form/tree/master). 
**eg** one case use other field called arabic_name and is saved in a custom_reg_info model.
image

**How does this PR modify the current behavior?**
If you dont use the setting `REGISTRATION_EXTENSION_FORM` the post flow would be the same. 

https://github.com/openedx/edx-platform/blob/open-release/palm.4/openedx/core/djangoapps/user_authn/views/registration_form.py#L298-L305
That function return None and then the function `do_create_account`
https://github.com/openedx/edx-platform/blob/open-release/palm.4/common/djangoapps/student/helpers.py#L674
has that default value.

**Why do we want this?**
Custom reg form is a feature that [edx-platform upstream](https://github.com/openedx/edx-platform/blob/open-release/palm.4/openedx/core/djangoapps/user_authn/views/register.py#L215) support. So if Someone has it and wants to create a user using eox-core, this feature allows him also to save the data in the custom_reg_form model if they have configured `REGISTRATION_EXTENSION_FORM` and the main function `do_create_account` hast that default value.
https://github.com/openedx/edx-platform/blob/open-release/palm.4/common/djangoapps/student/helpers.py#L674

``` json
"EDNX_CUSTOM_REGISTRATION_FIELDS": [
        {
            "label": "arabicname",
            "name": "arabic_name",
            "type": "text"
        }
]
```

**Review by MaferMazu — APPROVED** [review]
Thanks, @johanv26, looks good to me.

**Review by bra-i-am — APPROVED** [review]
Working as expected!

**Comment by bra-i-am** [comment]
Hi everyone, should this PR be merged right now or is there something lacking?

**Comment by luisfelipec95** [comment]
Hello @johanseto,  should this PR be merged right now or is there something lacking?

**Comment by andrey-canon** [comment]
Hi @luisfelipec95, @bra-i-am, this pr is ready and there is nothing to add, however we are not aware of your merging process (bumpversion, tags, merge commit  ... etc) that's why we prefer that you merge this

**Pull request merged**
