### PR TITLE
(DS-338) fix(ci): update bumpversion workflow to make changelog publish

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
## Description

This PR update the CHANGELOG file and the bumpversion workfloy to publish the changelog when a PR is merge.

### CODE REVIEW

**Review by dcoa — DISMISSED** [review]

**Review by Henrrypg — APPROVED** [review]
It looks good for me

**Comment by MaferMazu** [comment]
The change looks good to me, but I think this is not a feature; it is a ci commit.

**Comment by JuanDavidBuitrago** [comment]
> The change looks good to me, but I think this is not a feature but a ci commit. So I made this comment in favor of doing a minor upgrade instead of a major. What do you think?

It could be ci commit, but with feat we make a minor. I'm going to change this to ci commit. Tanks!! :smiley:

**Comment by JuanDavidBuitrago** [comment]
Changed commit label. @Henrrypg and @dcoa could approve again, please.

**Review by Henrrypg — APPROVED** [review]

**Review by Alec4r — APPROVED** [review]

**Pull request merged**
