### PR TITLE
Use username max length defined in edx-platform

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Comment by felipemontoya** [comment]
With this in mind we would also not need the users_i backend, right?

**Comment by morenol** [comment]
> With this in mind we would also not need the users_i backend, right?

No, let me know if do you think that it would be better to remove that.

**Comment by felipemontoya** [comment]
I think so, yeah. Why leave code creating the I backend when it only
imports the H backend? Let's remove it for clarity

**Comment by felipemontoya** [comment]
:+1:

**Pull request merged**
